---
bootstrap_tar: "bootstrap-2017Q2-tools.tar.gz"
bootstrap_sha: "f61644da2871f1377774196fd3f2eb6c7c9db228"

libffi_tgz: "libffi-3.2.1nb3.tgz"
db4_tgz: "db4-4.8.30.tgz"
python_tgz: "python27-2.7.13nb1.tgz"
